development:
  adapter: mysql2
  database: scht_development
  encoding: utf8mb4
  username: root
  password: hxklpf
  host: 127.0.0.1
  pool: 16
  timeout: 5000
  collation: utf8mb4_general_ci

test:
  adapter: mysql2
  encoding: utf8mb4
  database: scht_test
  username: root
  password: hxklpf
  host: 127.0.0.1
  pool: 5
  timeout: 5000
  collation: utf8mb4_general_ci

production:
  adapter: mysql2
  database: scht
  encoding: utf8mb4
  username: root
  password: hxklpf
  host: 127.0.0.1
  pool: 5
  timeout: 5000
  collation: utf8mb4_general_ci
